name: structured_document
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - aiohappyeyeballs=2.4.0=py311hecd8cb5_0
  - aiohttp=3.10.5=py311h46256e1_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - annotated-types=0.6.0=py311hecd8cb5_0
  - anyio=4.2.0=py311hecd8cb5_0
  - appnope=0.1.2=py311hecd8cb5_1001
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py311h6c40b1e_0
  - arrow-cpp=16.1.0=hc0a701b_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-lru=2.0.4=py311hecd8cb5_0
  - attrs=23.1.0=py311hecd8cb5_0
  - aws-c-auth=0.6.19=h6c40b1e_0
  - aws-c-cal=0.5.20=h3333b6a_0
  - aws-c-common=0.8.5=h6c40b1e_0
  - aws-c-compression=0.2.16=h6c40b1e_0
  - aws-c-event-stream=0.2.15=hcec6c5f_0
  - aws-c-http=0.6.25=h6c40b1e_0
  - aws-c-io=0.13.10=h6c40b1e_0
  - aws-c-mqtt=0.7.13=h6c40b1e_0
  - aws-c-s3=0.1.51=h6c40b1e_0
  - aws-c-sdkutils=0.1.6=h6c40b1e_0
  - aws-checksums=0.1.13=h6c40b1e_0
  - aws-crt-cpp=0.18.16=hcec6c5f_0
  - aws-sdk-cpp=1.10.55=h61975a4_0
  - babel=2.11.0=py311hecd8cb5_0
  - beautifulsoup4=4.12.3=py311hecd8cb5_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - boost-cpp=1.82.0=ha357a0b_2
  - bottleneck=1.3.7=py311hb3a5e46_0
  - brotli=1.0.9=h6c40b1e_8
  - brotli-bin=1.0.9=h6c40b1e_8
  - brotli-python=1.0.9=py311hcec6c5f_8
  - bzip2=1.0.8=h6c40b1e_6
  - c-ares=1.19.1=h6c40b1e_0
  - ca-certificates=2024.9.24=hecd8cb5_0
  - catalogue=2.0.10=py311hecd8cb5_0
  - certifi=2024.8.30=py311hecd8cb5_0
  - cffi=1.16.0=py311h6c40b1e_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.1.7=py311hecd8cb5_0
  - cloudpathlib=0.16.0=py311hecd8cb5_1
  - colorama=0.4.6=py311hecd8cb5_0
  - comm=0.2.1=py311hecd8cb5_0
  - confection=0.1.4=py311h85bffb1_0
  - conllu=5.0.2=pyhd8ed1ab_0
  - contourpy=1.2.0=py311ha357a0b_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cymem=2.0.6=py311hcec6c5f_0
  - cython-blis=0.7.9=py311hb3a5e46_0
  - datasets=2.19.1=py311hecd8cb5_0
  - debugpy=1.6.7=py311hcec6c5f_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - dill=0.3.8=py311hecd8cb5_0
  - executing=0.8.3=pyhd3eb1b0_0
  - filelock=3.13.1=py311hecd8cb5_0
  - fonttools=4.51.0=py311h6c40b1e_0
  - freetype=2.12.1=hd8bbffd_0
  - frozenlist=1.4.0=py311h6c40b1e_0
  - fsspec=2024.3.1=py311hecd8cb5_0
  - gflags=2.2.2=hcec6c5f_1
  - glog=0.5.0=hcec6c5f_1
  - gmp=6.2.1=he9d5cce_3
  - gmpy2=2.1.2=py311h1c2e9e1_0
  - h11=0.14.0=py311hecd8cb5_0
  - httpcore=1.0.2=py311hecd8cb5_0
  - httpx=0.27.0=py311hecd8cb5_0
  - huggingface_hub=0.24.6=py311hecd8cb5_0
  - icu=73.1=hcec6c5f_0
  - idna=3.7=py311hecd8cb5_0
  - importlib-metadata=7.0.1=py311hecd8cb5_0
  - intel-openmp=2022.1.0=haf03e11_3719
  - ipykernel=6.28.0=py311hecd8cb5_0
  - ipython=8.27.0=py311hecd8cb5_0
  - jedi=0.19.1=py311hecd8cb5_0
  - jinja2=3.1.4=py311hecd8cb5_0
  - joblib=1.4.2=py311hecd8cb5_0
  - jpeg=9e=h46256e1_3
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.19.2=py311hecd8cb5_0
  - jsonschema-specifications=2023.7.1=py311hecd8cb5_0
  - jupyter-lsp=2.2.0=py311hecd8cb5_0
  - jupyter_client=8.6.0=py311hecd8cb5_0
  - jupyter_core=5.7.2=py311hecd8cb5_0
  - jupyter_events=0.10.0=py311hecd8cb5_0
  - jupyter_server=2.14.1=py311hecd8cb5_0
  - jupyter_server_terminals=0.4.4=py311hecd8cb5_1
  - jupyterlab=4.2.5=py311hecd8cb5_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.27.3=py311hecd8cb5_0
  - kiwisolver=1.4.4=py311hcec6c5f_0
  - krb5=1.20.1=h428f121_1
  - langcodes=3.3.0=pyhd3eb1b0_0
  - lcms2=2.12=hf1fd2bf_0
  - lerc=3.0=he9d5cce_0
  - libabseil=20240116.2=cxx17_h548131f_0
  - libboost=1.82.0=hf53b9f2_2
  - libbrotlicommon=1.0.9=h6c40b1e_8
  - libbrotlidec=1.0.9=h6c40b1e_8
  - libbrotlienc=1.0.9=h6c40b1e_8
  - libcurl=8.9.1=h3a17b82_0
  - libcxx=19.1.1=hf95d169_0
  - libdeflate=1.17=hb664fd8_1
  - libedit=3.1.20230828=h6c40b1e_0
  - libev=4.33=h9ed2024_1
  - libevent=2.1.12=h04015c4_1
  - libffi=3.4.4=hecd8cb5_1
  - libgfortran=5.0.0=11_3_0_hecd8cb5_28
  - libgfortran5=11.3.0=h9dfd629_28
  - libgrpc=1.62.2=hf2926fd_0
  - libiconv=1.16=h6c40b1e_3
  - libjpeg-turbo=2.0.0=hca72f7f_0
  - libnghttp2=1.57.0=h9beae6a_0
  - libopenblas=0.3.21=h54e7dc3_0
  - libpng=1.6.39=h6c40b1e_0
  - libprotobuf=4.25.3=h34eed0b_0
  - libsentencepiece=0.2.0=h866d8ad_2
  - libsodium=1.0.18=h1de35cc_0
  - libssh2=1.11.0=hf20ceda_0
  - libthrift=0.15.0=h70b4b81_2
  - libtiff=4.5.1=hcec6c5f_0
  - libwebp-base=1.3.2=h6c40b1e_0
  - llvm-openmp=19.1.1=h545e0da_0
  - lz4-c=1.9.4=hcec6c5f_1
  - markdown-it-py=2.2.0=py311hecd8cb5_1
  - markupsafe=2.1.3=py311h6c40b1e_0
  - matplotlib-base=3.9.2=py311hc25a08b_0
  - matplotlib-inline=0.1.6=py311hecd8cb5_0
  - mdurl=0.1.0=py311hecd8cb5_0
  - mistune=2.0.4=py311hecd8cb5_0
  - mkl=2023.2.0=h54c2260_50500
  - mkl-service=2.4.0=py311h6c40b1e_1
  - mkl_fft=1.3.10=py311h10957f0_2
  - mkl_random=1.2.8=py311h58b9809_1
  - mpc=1.1.0=h6ef4df4_1
  - mpfr=4.0.2=h9066e36_1
  - mpmath=1.3.0=py311hecd8cb5_0
  - multidict=6.0.4=py311h6c40b1e_0
  - multiprocess=0.70.15=py311hecd8cb5_0
  - murmurhash=1.0.7=py311hcec6c5f_0
  - nbclient=0.8.0=py311hecd8cb5_0
  - nbconvert=7.10.0=py311hecd8cb5_0
  - nbformat=5.9.2=py311hecd8cb5_0
  - ncurses=6.4=hcec6c5f_0
  - nest-asyncio=1.6.0=py311hecd8cb5_0
  - networkx=3.3=py311hecd8cb5_0
  - notebook=7.2.2=py311hecd8cb5_0
  - notebook-shim=0.2.3=py311hecd8cb5_0
  - numexpr=2.8.7=py311h728a8a3_0
  - numpy=1.26.4=py311h728a8a3_0
  - numpy-base=1.26.4=py311h53bf9ac_0
  - openjpeg=2.5.2=hbf2204d_0
  - openssl=3.3.2=hd23fc13_0
  - orc=2.0.1=h5747287_0
  - overrides=7.4.0=py311hecd8cb5_0
  - packaging=24.1=py311hecd8cb5_0
  - pandas=2.2.2=py311he327ffe_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pathy=0.10.3=py311hecd8cb5_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pillow=10.4.0=py311h46256e1_0
  - pip=24.2=py311hecd8cb5_0
  - platformdirs=3.10.0=py311hecd8cb5_0
  - preshed=3.0.6=py311hcec6c5f_0
  - prometheus_client=0.14.1=py311hecd8cb5_0
  - prompt-toolkit=3.0.43=py311hecd8cb5_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py311h6c40b1e_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyarrow=16.1.0=py311he327ffe_0
  - pybind11-abi=4=hd3eb1b0_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=1.10.12=py311h6c40b1e_1
  - pydantic-core=2.20.1=py311hcc58cb1_0
  - pygments=2.15.1=py311hecd8cb5_1
  - pyparsing=3.1.2=py311hecd8cb5_0
  - pysocks=1.7.1=py311hecd8cb5_0
  - python=3.11.9=hf27a42d_0
  - python-dateutil=2.9.0post0=py311hecd8cb5_2
  - python-fastjsonschema=2.16.2=py311hecd8cb5_0
  - python-json-logger=2.0.7=py311hecd8cb5_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python-xxhash=2.0.2=py311h6c40b1e_1
  - python_abi=3.11=2_cp311
  - pytorch=2.2.2=py3.11_0
  - pytz=2024.1=py311hecd8cb5_0
  - pyyaml=6.0.1=py311h6c40b1e_0
  - pyzmq=25.1.2=py311hcec6c5f_0
  - re2=2022.04.01=he9d5cce_0
  - readline=8.2=hca72f7f_0
  - referencing=0.30.2=py311hecd8cb5_0
  - regex=2024.9.11=py311h46256e1_0
  - requests=2.32.3=py311hecd8cb5_0
  - rfc3339-validator=0.1.4=py311hecd8cb5_0
  - rfc3986-validator=0.1.1=py311hecd8cb5_0
  - rich=13.7.1=py311hecd8cb5_0
  - rpds-py=0.10.6=py311hf2ad997_0
  - safetensors=0.4.5=py311h907dbcc_0
  - scikit-learn=1.2.2=py311hcec6c5f_1
  - scipy=1.13.0=py311h224febf_0
  - seaborn=0.13.2=py311hecd8cb5_0
  - send2trash=1.8.2=py311hecd8cb5_0
  - sentencepiece=0.2.0=hecd8cb5_2
  - sentencepiece-python=0.2.0=py311h1383577_2
  - sentencepiece-spm=0.2.0=h866d8ad_2
  - setuptools=75.1.0=py311hecd8cb5_0
  - shellingham=1.5.0=py311hecd8cb5_0
  - six=1.16.0=pyhd3eb1b0_1
  - smart_open=5.2.1=py311hecd8cb5_0
  - snappy=1.2.1=h6d0c2b6_0
  - sniffio=1.3.0=py311hecd8cb5_0
  - soupsieve=2.5=py311hecd8cb5_0
  - spacy=3.5.3=py311h7966749_0
  - spacy-legacy=3.0.12=py311hecd8cb5_0
  - spacy-loggers=1.0.4=py311hecd8cb5_0
  - spacy-model-fr_core_news_sm=3.5.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h6c40b1e_0
  - srsly=2.4.8=py311hcec6c5f_1
  - stack_data=0.2.0=pyhd3eb1b0_0
  - sympy=1.13.2=py311hecd8cb5_0
  - tbb=2021.8.0=ha357a0b_0
  - terminado=0.17.1=py311hecd8cb5_0
  - thinc=8.1.10=py311h7966749_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tinycss2=1.2.1=py311hecd8cb5_0
  - tk=8.6.14=h4d00af3_0
  - tokenizers=0.19.1=py311hb453228_0
  - torchaudio=2.2.2=py311_cpu
  - torchvision=0.17.2=py311_cpu
  - tornado=6.4.1=py311h46256e1_0
  - tqdm=4.66.5=py311h85bffb1_0
  - traitlets=5.14.3=py311hecd8cb5_0
  - transformers=4.41.2=py311hecd8cb5_0
  - typer=0.4.1=py311hecd8cb5_0
  - typing-extensions=4.11.0=py311hecd8cb5_0
  - typing_extensions=4.11.0=py311hecd8cb5_0
  - tzdata=2024a=h04d1e81_0
  - unicodedata2=15.1.0=py311h6c40b1e_0
  - urllib3=2.2.2=py311hecd8cb5_0
  - utf8proc=2.6.1=h6c40b1e_1
  - wasabi=0.9.1=py311hecd8cb5_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - weasel=0.3.4=py311hecd8cb5_0
  - webencodings=0.5.1=py311hecd8cb5_1
  - websocket-client=1.8.0=py311hecd8cb5_0
  - wheel=0.44.0=py311hecd8cb5_0
  - xxhash=0.8.0=h9ed2024_3
  - xz=5.4.6=h6c40b1e_1
  - yaml=0.2.5=haf1e3a3_0
  - yarl=1.11.0=py311h46256e1_0
  - zeromq=4.3.5=hcec6c5f_0
  - zipp=3.20.2=py311hecd8cb5_0
  - zlib=1.2.13=h4b97444_1
  - zstd=1.5.6=h138b38a_0
prefix: /opt/anaconda3/envs/structured_document
